server:
  port: ${SERVER_PORT}

spring:
  application:
    name: karvio-notification-service

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    karvio: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"